//create user baru
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Agus tes",
    "email": "agustes@gmail.com",
    "password": "agustes123",
    "confPassword": "agustes123",
    "role": "user"
}

####################################################################

//get semua user
GET http://localhost:5000/users

####################################################################

//get 1 user
GET http://localhost:5000/users/2174cfa3-888a-40e5-88c8-90e712739136

####################################################################

//update user
PATCH  http://localhost:5000/users/2174cfa3-888a-40e5-88c8-90e712739136
Content-Type: application/json

{
    "name": "Niam   tes",
    "email": "niamtes@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

####################################################################

//delete user
DELETE http://localhost:5000/users/1e8ba75b-b119-492c-aeb8-5cf2a20ce107
