// login USER
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "muna@gmail.com",
    "password": "muna123"
}

####################################################################

// profil me
GET http://localhost:5000/me

####################################################################

// logout USER
DELETE  http://localhost:5000/logout


################################################################################################################################################
//--------------------------------------------------------------------------------------------------------------------------------------------//
################################################################################################################################################


// create USER baru
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "teguh",
    "email": "teguh@gmail.com",
    "password": "teguh123",
    "confPassword": "teguh123",
    "role": "user"
}

####################################################################


// update USER
PATCH  http://localhost:5000/users/b106a1f7-f1e7-4636-8435-d5e1c34a1d1b
Content-Type: application/json

{
    "name": "muna updated",
    "email": "muna@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

####################################################################

// delete USER
DELETE http://localhost:5000/users/b106a1f7-f1e7-4636-8435-d5e1c34a1d1b

// get semua USER
GET http://localhost:5000/users

####################################################################

// get 1 USER
GET http://localhost:5000/users/b106a1f7-f1e7-4636-8435-d5e1c34a1d1b


################################################################################################################################################
//--------------------------------------------------------------------------------------------------------------------------------------------//
################################################################################################################################################


// create data PRODUCT baru
POST http://localhost:5000/product
Content-Type: application/json

{
    "name": "produk muna 2",
    "price": 2222
}

####################################################################

PATCH  http://localhost:5000/product/
Content-Type: application/json

{
    "name": "produk niam 1 updated",
    "price": 11111
}

####################################################################

// delete PRODUCT
DELETE http://localhost:5000/product/

####################################################################

// get all PRODUCT
GET http://localhost:5000/product

####################################################################

// get 1 PRODUCT
GET http://localhost:5000/product/